version: '3.4'

services:
  client:
    build:
      context: ./calculatorEndterm/calculator_client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty:
      true
    depends_on:
      - server
  server:
    build:
      context: ./calculatorEndterm/calculator_server
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    tty:
      true